# Generated by Django 4.1.3 on 2022-11-26 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todotasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author_ip',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='done_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
